### ISSUE TITLE
간단한 제안?

### ISSUE THREAD

**Issue by agrajak** [atobaum/galois#17]
## 설명 
저도 늘 생각과 기록을 어떻게 정리하면 좋을지에 대해서 고민이 많았는데요 응원합니다!!
원래는 노션을 쓰다가 최근에는 Roam Research을 사용하고 있는데 (이미 아시는 서비스 일 수도 있음..) 이거도 문서들을 서로 링크한다는 개념은 편한데 사용하다보니까 나름대로 불편한 점이 많더라구요..
이거 참고하셔도 좋은 레퍼런스가 될 거 같아요!

**Comment by atobaum** [comment]
감사합니다. 다른 사람이 볼거라고 생각 못하고 있었는데 부끄럽네요 ㅎㅎ
전에 이것저것 찾아보다가 Roam 대충 봤었는데 workflowy 같이 리스트 중심인거 같았었는데 좋은가요? 유료여서 써보진 않았는데..

딱 맘에드는 앱을 찾기가 어렵네요.
